version: '3'
services:
  registry:
    container_name: docker_registry
    restart: always
    image: registry:2
    environment:
      - "REGISTRY_HTTP_TLS_CERTIFICATE=/certs/live/registry.goldtect.cn/fullchain.pem"
      - "REGISTRY_HTTP_TLS_KEY=/certs/live/registry.goldtect.cn/privkey.pem"
      - "REGISTRY_AUTH=htpasswd"
      - "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm"
      - "REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd"
      - "REGISTRY_HTTP_SECRET=Admin01!"
      #- "REGISTRY_STORAGE_DELETE_ENABLED=true"
    volumes:
      - ./registry:/var/lib/registry
      - ./letsencrypt/:/certs
      - ./auth:/auth
    ports:
      - "9999:5000"
      
  ui:
    container_name: docker_registry_ui
    image: jc21/registry-ui
    environment:
      - NODE_ENV=production
      - REGISTRY_HOST=registry:5000
      - REGISTRY_SSL=true
      - REGISTRY_DOMAIN=registry.goldtect.cn:9999
      - REGISTRY_USER=jinweijie
      - REGISTRY_PASS=Admin01!
      #- REGISTRY_STORAGE_DELETE_ENABLED=true
    links:
      - registry
    restart: always

  registry-proxy:
    container_name: docker_registry_proxy
    image: jc21/registry-ui-proxy
    depends_on:
      - ui
      - registry
    links:
      - ui
      - registry
    restart: always

  lets-nginx:
    container_name: docker_registry_lets_nginx_certs
    image: smashwilson/lets-nginx
    restart: always
    volumes:
      - "./cache:/cache"
      - "./letsencrypt:/etc/letsencrypt"
    links:
      - registry:registry
    environment:
      - "EMAIL=jinweijie@gmail.com"
      - "DOMAIN=registry.goldtect.cn"
      - "UPSTREAM=registry-proxy:80"
    ports:
      - "9998:443"
